[project]
name = "zm08"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5"
]

[project.scripts]
zm08 = "zm08.main:app"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
